name: build
on:
  schedule:
    - cron:  '30 13 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: prepare Selenium
      uses: nanasess/setup-chromedriver@master
      with:
        chromedriver-version: 'latest'
    
    - name: execute py script
      run: |
        python main.py

    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "Data Added" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main